/**
 * SEO-Targeted Multilingual Blog Generator
 * 
 * Forked from generate-articles.ts — specifically targets SEO keywords that 
 * 9anonai.com needs to rank for on Google. Generates blog articles in 3 languages
 * (AR, EN, FR) focused on the high-intent and long-tail keywords.
 * 
 * IMPORTANT: This does NOT modify generate-articles.ts — that script is still
 * used for general blog generation.
 * 
 * @module scripts/generate-seo-articles
 * @requires OPENROUTER_API_KEY set in environment
 */

import dotenv from "dotenv";
dotenv.config();

import OpenAI from "openai";
import * as fs from "fs";
import * as path from "path";
import { getTable } from "../src/services/db";
import { getEmbedding } from "../src/services/bi";

// Configure OpenAI client with OpenRouter
const client = new OpenAI({
    baseURL: "https://openrouter.ai/api/v1",
    apiKey: process.env.OPENROUTER_API_KEY,
    defaultHeaders: {
        "HTTP-Referer": "https://github.com/moroccan-legal-ai",
        "X-Title": "9anon - SEO Blog Generator",
    },
});

/**
 * SEO-targeted blog topics — each one maps to specific keywords the site
 * needs to rank for. These are NOT randomly generated by LLM; they are
 * strategically chosen to match the user's target keyword list.
 */
const SEO_TOPICS = [
    {
        slug: "legal-ai-assistant-morocco-guide",
        titles: {
            ar: "مساعد قانوني ذكي في المغرب: دليلك الشامل للاستشارة القانونية بالذكاء الاصطناعي",
            en: "Legal AI Assistant in Morocco: Your Complete Guide to AI-Powered Legal Help",
            fr: "Assistant Juridique IA au Maroc : Guide Complet de l'Aide Juridique par Intelligence Artificielle",
        },
        descriptions: {
            ar: "تعرف على كيفية استخدام مساعد قانوني ذكي في المغرب للحصول على استشارة قانونية فورية ومجانية",
            en: "Learn how AI legal assistants work in Morocco and how you can get free, instant legal advice online",
            fr: "Découvrez comment les assistants juridiques IA fonctionnent au Maroc et obtenez des conseils juridiques gratuits",
        },
        searchQuery: "الذكاء الاصطناعي القانوني المغرب مساعد قانوني",
        keywords: ["legal AI assistant Morocco", "AI lawyer Morocco", "assistant juridique IA Maroc", "مساعد قانوني ذكي المغرب", "online legal advice Morocco", "conseil juridique en ligne Maroc"],
    },
    {
        slug: "divorce-procedure-morocco-complete-guide",
        titles: {
            ar: "إجراءات الطلاق في المغرب: الدليل الكامل لحقوقك القانونية",
            en: "Divorce Procedure in Morocco: Complete Legal Guide to Your Rights",
            fr: "Procédure de Divorce au Maroc : Guide Juridique Complet de Vos Droits",
        },
        descriptions: {
            ar: "كل ما تحتاج معرفته عن إجراءات الطلاق في المغرب وحقوقك القانونية حسب مدونة الأسرة",
            en: "Everything you need to know about divorce proceedings in Morocco and your legal rights under the Moudawana",
            fr: "Tout ce que vous devez savoir sur la procédure de divorce au Maroc et vos droits selon la Moudawana",
        },
        searchQuery: "الطلاق في المغرب إجراءات مدونة الأسرة",
        keywords: ["divorce lawyer Morocco online", "divorce Maroc procédure", "الطلاق في المغرب إجراءات", "inheritance law Morocco help", "droit successoral Maroc"],
    },
    {
        slug: "employee-rights-morocco-labor-law",
        titles: {
            ar: "حقوق الموظف في المغرب: ماذا يقول قانون الشغل عن حمايتك",
            en: "Employee Rights in Morocco: What the Labor Code Says About Your Protection",
            fr: "Droits des Employés au Maroc : Ce Que le Code du Travail Dit de Votre Protection",
        },
        descriptions: {
            ar: "اكتشف حقوقك كموظف في المغرب حسب مدونة الشغل: العقد، الأجر، الإجازات، الفصل التعسفي",
            en: "Discover your rights as an employee in Morocco under the Labor Code: contracts, wages, leave, wrongful dismissal",
            fr: "Découvrez vos droits en tant qu'employé au Maroc selon le Code du Travail : contrats, salaires, congés, licenciement",
        },
        searchQuery: "حقوق الموظف المغرب قانون الشغل مدونة الشغل",
        keywords: ["employee rights Morocco", "labor law advice Morocco", "droits des employés Maroc", "حقوق الموظف في المغرب", "droit du travail Maroc conseil", "قانون الشغل المغرب استشارة"],
    },
    {
        slug: "tenant-rights-morocco-rental-disputes",
        titles: {
            ar: "حقوق المستأجر في المغرب: كيف تحمي نفسك من النزاعات الإيجارية",
            en: "Tenant Rights in Morocco: How to Protect Yourself from Rental Disputes",
            fr: "Droits du Locataire au Maroc : Comment Vous Protéger des Litiges Locatifs",
        },
        descriptions: {
            ar: "دليل شامل لحقوق المستأجر في المغرب وكيفية تقديم شكوى في حالة النزاعات الإيجارية",
            en: "Comprehensive guide to tenant rights in Morocco and how to file complaints for rental disputes",
            fr: "Guide complet des droits du locataire au Maroc et comment déposer une plainte en cas de litige locatif",
        },
        searchQuery: "حقوق المستأجر المغرب نزاع ايجاري",
        keywords: ["tenant rights Morocco", "how to file complaint in Morocco", "litige locatif Maroc", "حقوق المستأجر في المغرب"],
    },
    {
        slug: "starting-business-morocco-company-registration",
        titles: {
            ar: "تسجيل شركة في المغرب: دليل المساعدة القانونية للمقاولين الجدد",
            en: "Starting a Business in Morocco: Legal Guide to Company Registration",
            fr: "Créer une Société au Maroc : Guide Juridique pour l'Enregistrement d'Entreprise",
        },
        descriptions: {
            ar: "خطوات تسجيل شركة في المغرب مع مساعدة قانونية. كل ما يحتاجه المقاول الجديد",
            en: "Step-by-step legal guide to registering a company in Morocco. Everything new entrepreneurs need",
            fr: "Guide juridique étape par étape pour créer une société au Maroc. Tout pour les nouveaux entrepreneurs",
        },
        searchQuery: "تسجيل شركة المغرب إنشاء مقاولة القانون التجاري",
        keywords: ["company registration legal help Morocco", "startup legal advice Morocco", "création société Maroc assistance juridique", "conseil juridique startup Maroc", "تسجيل شركة في المغرب مساعدة", "legal support for startups Morocco"],
    },
    {
        slug: "contract-review-ai-morocco-business",
        titles: {
            ar: "صياغة ومراجعة العقود في المغرب بالذكاء الاصطناعي",
            en: "AI Contract Review in Morocco: Smarter Business Contract Management",
            fr: "Révision de Contrats par IA au Maroc : Gestion Intelligente des Contrats d'Affaires",
        },
        descriptions: {
            ar: "كيف يساعدك الذكاء الاصطناعي في صياغة ومراجعة عقود الشركات حسب القانون المغربي",
            en: "How AI helps you draft and review business contracts under Moroccan law",
            fr: "Comment l'IA vous aide à rédiger et réviser les contrats d'affaires selon le droit marocain",
        },
        searchQuery: "صياغة عقد شركة المغرب مراجعة عقود",
        keywords: ["contract review AI Morocco", "business contract review Morocco", "rédaction contrat Maroc", "صياغة عقد شركة المغرب"],
    },
    {
        slug: "commercial-law-morocco-business-compliance",
        titles: {
            ar: "القانون التجاري المغربي: دليل الامتثال القانوني للشركات",
            en: "Moroccan Commercial Law: Business Compliance Guide for Companies",
            fr: "Droit Commercial Marocain : Guide de Conformité Juridique pour les Entreprises",
        },
        descriptions: {
            ar: "كل ما تحتاج معرفته عن القانون التجاري المغربي والامتثال القانوني للشركات الصغيرة والمتوسطة",
            en: "Everything you need to know about Moroccan commercial law and legal compliance for SMEs",
            fr: "Tout sur le droit commercial marocain et la conformité juridique pour les PME",
        },
        searchQuery: "القانون التجاري المغربي الامتثال القانوني الشركات",
        keywords: ["Moroccan commercial law advice", "corporate legal compliance Morocco", "droit commercial Maroc conseil", "conformité légale entreprise Maroc", "القانون التجاري المغربي", "الامتثال القانوني للشركات المغرب", "SME legal services Morocco"],
    },
    {
        slug: "inheritance-law-morocco-succession-rights",
        titles: {
            ar: "الإرث في القانون المغربي: حقوقك في الميراث والتركة",
            en: "Inheritance Law in Morocco: Your Rights to Succession and Estate",
            fr: "Droit Successoral au Maroc : Vos Droits en Matière d'Héritage et de Succession",
        },
        descriptions: {
            ar: "دليل شامل لقانون الإرث في المغرب وحقوق الورثة حسب مدونة الأسرة والشريعة الإسلامية",
            en: "Comprehensive guide to inheritance law in Morocco and heirs' rights under the Moudawana",
            fr: "Guide complet du droit successoral au Maroc et des droits des héritiers selon la Moudawana",
        },
        searchQuery: "الإرث في القانون المغربي مدونة الأسرة الميراث",
        keywords: ["inheritance law Morocco help", "droit successoral Maroc", "الإرث في القانون المغربي"],
    },
    {
        slug: "tax-compliance-morocco-business-guide",
        titles: {
            ar: "الامتثال الضريبي للشركات في المغرب: دليل قانوني شامل",
            en: "Tax Compliance for Businesses in Morocco: Comprehensive Legal Guide",
            fr: "Conformité Fiscale des Entreprises au Maroc : Guide Juridique Complet",
        },
        descriptions: {
            ar: "كل ما يحتاجه أصحاب الشركات في المغرب عن الامتثال الضريبي والالتزامات القانونية",
            en: "Everything business owners in Morocco need to know about tax compliance and legal obligations",
            fr: "Tout ce que les entrepreneurs au Maroc doivent savoir sur la conformité fiscale et les obligations légales",
        },
        searchQuery: "الامتثال الضريبي الشركات المغرب الضرائب",
        keywords: ["tax compliance legal help Morocco", "SME legal services Morocco", "conformité légale entreprise Maroc", "aide juridique entreprise Maroc"],
    },
    {
        slug: "online-legal-consultation-morocco-chatbot",
        titles: {
            ar: "استشارة قانونية اونلاين في المغرب: كيف يعمل الشات بوت القانوني",
            en: "Online Legal Consultation in Morocco: How Legal Chatbots Work",
            fr: "Consultation Juridique en Ligne au Maroc : Comment Fonctionnent les Chatbots Juridiques",
        },
        descriptions: {
            ar: "تعرف على كيفية الحصول على استشارة قانونية اونلاين مجانية في المغرب عبر الذكاء الاصطناعي",
            en: "Learn how to get free online legal consultation in Morocco through AI-powered legal chatbots",
            fr: "Découvrez comment obtenir une consultation juridique gratuite en ligne au Maroc via les chatbots IA",
        },
        searchQuery: "استشارة قانونية اونلاين المغرب شات بوت قانوني",
        keywords: ["legal chatbot Morocco", "online legal advice Morocco", "chatbot juridique Maroc", "consultation juridique digitale Maroc", "شات بوت قانوني المغرب", "استشارة قانونية اونلاين المغرب", "Moroccan legal consultation online"],
    },
];

/**
 * Language configuration for article generation
 */
const LANGUAGES = [
    { code: "ar", name: "Arabic", suffix: "", direction: "rtl" },
    { code: "en", name: "English", suffix: ".en", direction: "ltr" },
    { code: "fr", name: "French", suffix: ".fr", direction: "ltr" },
];

/**
 * @description Generated blog article shape
 */
interface GeneratedBlog {
    slug: string;
    language: string;
    title: string;
    description: string;
    content: string;
    sources: string[];
    generatedAt: Date;
}

/**
 * @description Blog topic shape with translations
 */
interface BlogTopic {
    slug: string;
    titles: { ar: string; en: string; fr: string };
    descriptions: { ar: string; en: string; fr: string };
    searchQuery: string;
    keywords: string[];
}

/**
 * Search legal documents using the RAG system
 * @param {string} query - Search query in Arabic
 * @param {number} limit - Max results
 * @returns Array of legal doc results
 */
async function searchLegalDocs(query: string, limit: number = 5): Promise<any[]> {
    try {
        const table = await getTable();
        if (!table) {
            console.warn("   ⚠️  RAG table not found, proceeding without context.");
            return [];
        }
        const queryEmbedding = await getEmbedding(query);
        const results = await table.search(queryEmbedding).limit(limit).toArray();
        return results.map((r: any, idx: number) => ({
            id: r.id || `doc_${idx}`,
            text: r.text,
            source_file: r.source_file,
            category: r.category,
            subcategory: r.subcategory,
            document_name: r.document_name,
        }));
    } catch (error) {
        console.error("   ❌ Error searching legal docs:", error);
        return [];
    }
}

/**
 * Build context string from RAG results for the LLM
 * @param {any[]} sources - Array of legal document sources
 * @returns Formatted context string
 */
function buildContext(sources: any[]): string {
    if (sources.length === 0) return "";
    return sources.map((doc, i) => {
        return `[Reference ${i + 1}]: ${doc.document_name || "Legal Document"}
Category: ${doc.category || "General"}${doc.subcategory ? ` > ${doc.subcategory}` : ""}
---
${doc.text}
---`;
    }).join("\n\n");
}

/**
 * Generate a single blog article in a specific language.
 * 
 * WHY the prompt is so specific: each article targets exact SEO keyword phrases
 * that need to appear naturally in the content for Google ranking.
 * 
 * @param {BlogTopic} topic - The SEO topic config
 * @param {typeof LANGUAGES[0]} language - Target language
 * @param {string} context - RAG context from legal docs
 * @returns Generated blog object
 */
async function generateBlogInLanguage(
    topic: BlogTopic,
    language: typeof LANGUAGES[0],
    context: string,
): Promise<GeneratedBlog> {
    console.log(`      🌐 [${language.name}] Generating...`);

    const languageInstructions: Record<string, string> = {
        ar: `اكتب المقال باللغة العربية الفصحى. استخدم أسلوبًا واضحًا ومفهومًا للقارئ العادي.
لا تستخدم الرموز التعبيرية (emojis) أبدًا.
استخدم علامات الترقيم العربية الصحيحة.`,
        en: `Write the article in clear, professional English accessible to non-lawyers.
Never use emojis.
Use proper British/American English grammar and punctuation.`,
        fr: `Rédigez l'article en français clair et professionnel, accessible aux non-juristes.
N'utilisez jamais d'emojis.
Utilisez une grammaire et une ponctuation françaises correctes.`,
    };

    // SEO-optimized system prompt — ensures keywords appear naturally in the content
    const systemPrompt = `You are an expert legal content writer specializing in Moroccan law and SEO.
Your task is to write a professional, educational blog article OPTIMIZED FOR GOOGLE SEARCH.

${languageInstructions[language.code]}

SEO & WRITING GUIDELINES:
1. Write in clear, accessible language that non-lawyers can understand
2. NATURALLY incorporate these target keywords throughout the article: ${topic.keywords.join(", ")}
3. Structure with clear H2 (##) and H3 (###) headings — use keyword-rich headings
4. Include specific references to Moroccan laws, codes, and articles when available
5. Include practical examples and real-world applications
6. Mention 9anon AI as a free tool for getting legal help on this topic
7. Target length: 1000-1500 words (detailed blog post)
8. Use proper markdown formatting throughout
9. NEVER use emojis
10. Include internal linking suggestion at the end: mention 9anon AI chatbot

ARTICLE STRUCTURE:
- SEO-optimized introduction (2-3 paragraphs, include primary keyword in first paragraph)
- 4-5 main sections with practical, keyword-rich information
- A section about how 9anon AI can help with this legal topic
- Conclusion with key takeaways

At the end, add this exact section:
---

### Related Search Terms
9anoun ai, 9anon ai, kanon ai, kanoun ai, qanon ai, qanoun ai`;

    const userPrompt = context
        ? `Based on the following legal references from Moroccan law:

${context}

---

Write a blog article with title: "${topic.titles[language.code as keyof typeof topic.titles]}"

SEO Keywords to naturally include: ${topic.keywords.join(", ")}

Generate a comprehensive, SEO-optimized blog article that educates readers and ranks on Google.`
        : `Write a blog article with title: "${topic.titles[language.code as keyof typeof topic.titles]}"

SEO Keywords to naturally include: ${topic.keywords.join(", ")}

Generate a comprehensive, SEO-optimized blog article that educates readers and ranks on Google.
Use your knowledge of Moroccan legal frameworks and cite specific laws where applicable.`;

    const response = await client.chat.completions.create({
        model: "google/gemini-3-flash-preview",
        messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
        ],
        max_tokens: 4000,
        temperature: 0.7,
    });

    const content = response.choices[0]?.message?.content || "";
    console.log(`      ✅ [${language.name}] Done (${content.length} chars)`);

    return {
        slug: topic.slug,
        language: language.code,
        title: topic.titles[language.code as keyof typeof topic.titles],
        description: topic.descriptions[language.code as keyof typeof topic.descriptions],
        content: content,
        sources: [],
        generatedAt: new Date(),
    };
}

/**
 * Save a blog article to the filesystem as a Markdown file with frontmatter
 * @param {GeneratedBlog} blog - The generated blog
 * @param {typeof LANGUAGES[0]} language - Language config
 * @param {string} outputDir - Output directory
 */
function saveBlog(blog: GeneratedBlog, language: typeof LANGUAGES[0], outputDir: string): void {
    const filename = `${blog.slug}${language.suffix}.md`;
    const filepath = path.join(outputDir, filename);

    const frontmatter = `---
title: "${blog.title}"
date: "${blog.generatedAt.toISOString().split("T")[0]}"
description: "${blog.description}"
---

`;
    const fullContent = frontmatter + blog.content;
    fs.writeFileSync(filepath, fullContent, "utf-8");
    console.log(`      💾 Saved: ${filename}`);
}

/**
 * Main execution — generates all SEO-targeted articles
 */
async function main(): Promise<void> {
    console.log("╔══════════════════════════════════════════════════════════════╗");
    console.log("║     🇲🇦 SEO-TARGETED BLOG GENERATOR                          ║");
    console.log(`║     Generating ${SEO_TOPICS.length} articles × 3 languages = ${SEO_TOPICS.length * 3} blog posts      ║`);
    console.log("╚══════════════════════════════════════════════════════════════╝\n");

    if (!process.env.OPENROUTER_API_KEY) {
        console.error("❌ ERROR: OPENROUTER_API_KEY environment variable is not set.");
        process.exit(1);
    }

    // Output to the FE blogs directory
    const outputDir = path.resolve(__dirname, "..", "..", "FE", "content", "blogs");

    if (!fs.existsSync(outputDir)) {
        console.error("❌ ERROR: Blogs directory not found:", outputDir);
        process.exit(1);
    }

    // Check which articles already exist to skip them
    const existingFiles = fs.readdirSync(outputDir);
    const existingSlugs = new Set(
        existingFiles.map(f => f.replace(/\.(en|fr)\.md$/, "").replace(/\.md$/, ""))
    );

    // Filter out already-generated topics
    const topicsToGenerate = SEO_TOPICS.filter(t => !existingSlugs.has(t.slug));

    if (topicsToGenerate.length === 0) {
        console.log("✅ All SEO articles already exist! Nothing to generate.");
        return;
    }

    console.log(`📁 Output directory: ${outputDir}`);
    console.log(`📝 ${topicsToGenerate.length} new topics to generate (${SEO_TOPICS.length - topicsToGenerate.length} already exist)\n`);

    const startTime = Date.now();
    let successCount = 0;
    let failCount = 0;

    for (let topicIdx = 0; topicIdx < topicsToGenerate.length; topicIdx++) {
        const topic = topicsToGenerate[topicIdx];
        console.log(`\n📝 [${topicIdx + 1}/${topicsToGenerate.length}] Topic: "${topic.titles.en}"`);

        // Search RAG for legal context
        console.log(`   🔍 Searching legal database...`);
        const sources = await searchLegalDocs(topic.searchQuery, 8);
        console.log(`   ✅ Found ${sources.length} relevant legal references`);

        const context = buildContext(sources);

        // Generate in all 3 languages
        for (let langIdx = 0; langIdx < LANGUAGES.length; langIdx++) {
            const language = LANGUAGES[langIdx];
            try {
                const blog = await generateBlogInLanguage(topic, language, context);
                blog.sources = sources.map(s => s.document_name || s.source_file || "Unknown");
                saveBlog(blog, language, outputDir);
                successCount++;

                // Small delay between API calls to avoid rate limiting
                await new Promise(resolve => setTimeout(resolve, 1500));
            } catch (error) {
                console.error(`      ❌ [${language.name}] Failed:`, error);
                failCount++;
            }
        }

        // Delay between topics
        if (topicIdx < topicsToGenerate.length - 1) {
            console.log(`   ⏳ Waiting 3 seconds before next topic...`);
            await new Promise(resolve => setTimeout(resolve, 3000));
        }
    }

    const duration = ((Date.now() - startTime) / 1000 / 60).toFixed(1);

    console.log("\n╔══════════════════════════════════════════════════════════════╗");
    console.log("║                    GENERATION COMPLETE                        ║");
    console.log("╚══════════════════════════════════════════════════════════════╝");
    console.log(`\n✅ Successfully generated: ${successCount} blog posts`);
    if (failCount > 0) console.log(`❌ Failed: ${failCount} blog posts`);
    console.log(`⏱️  Total time: ${duration} minutes`);
    console.log(`📁 Blogs saved to: ${outputDir}`);
}

main().catch(console.error);
